export const data=[
    {
        id:1,
        name:"kadakali",
        images:"kada.jpg",
        desc2:"Kathakali is an evolved dance form popular in the South Indian state of Kerala. This Indian classical dance involves storytelling activities through fascinating footwork and expressive gestures of face and hands accompanied by music and vocal performance.‘Kathakali’, an important genre in the Indian classical dance form, is associated with storytelling form of this art. It is the dance drama from the south Indian state of Kerala. Similar to other Indian classical dance arts, the story in ‘Kathakali’ is also communicated to audience through excellent footwork and impressive gestures of face and hands complimented with music and vocal performance. However it can be distinguished from the others through the intricate and vivid make-up, unique face masks and costumes worn by dancers as also from their style and movements that reflect the age-old martial arts and athletic conventions prevalent in Kerala and surrounding regions. Traditionally performed by male dancers, it developed in courts and theatres of Hindu regions contrary to other Indian classical dances which predominantly developed in Hindu temples and monastic schools. Although not clearly traceable, this classical dance form is considered to have originated from temple and folk arts that trace back to 1st millennium CE or before.",
        desc:"  Famous around the world, Kathakali's magnificence has won great admiration for the state of Kerala."
    },
    {
        id:2,
        name:"ottan thullal",
        images:"thu.jpg",
        desc2:"Ottan Thullal is a dance and poetic performance form of Kerala, India. It was introduced in the 18th century by Kunchan Nambiar, one of the Prachina Kavithrayam (three famous Malayalam language poets). It is accompanied by a mridangam (a barrel shaped double headed drum) or an idakka (drum and cymbal).Ottamthullal has its origins in the classical principles of Natya Shastra, a treatise on art originating in the 2nd century B.C. The word Thullal means to jump or leap about in the Tamil language. Tradition has it that Nambiar, the poet, fell asleep while playing the mizhavu for a Chakyar Koothu performance, inviting ridicule from the chakyar. In response, Nambiar developed Ottamthullal, which parodied prevalent sociopolitical questions and regional prejudices. The chakyar complained about Nambiar’s production to the king of Chembakassery. The king banned performances of Ottamthullal from the Ambalapuzha temple complex. Closely related art forms are Seethankan thullal and Parayan thullal. Mathur Panikkar popularized Ottamthullal for modern audiences. Ottamthullal competitions are held and the art form may be used to spread a social message.",
        desc:"  Across the length and breadth of Kerala’s landscape, Thullal performances have been the constant checks and reminders that have shaped our society. "
    },
    {
        id:3,
        name:"mohiniyattam",
        images:"mohiniyattam.jpg",
        desc2:"Mohiniattam or Mohiniyattam is an Indian classical dance form that evolved in the state of Kerala, India, and is counted among the two popular dance arts of the state, the other being Kathakali. Although its roots date back to the age-old Sanskrit Hindu text on performing arts called ‘Natya Shastra’, similar to other Indian classical dance forms, Mohiniattam adheres to the Lasya type that showcases a more graceful, gentle and feminine form of dancing. Mohiniattam derives its name from the word ‘Mohini’, a female avatar of Lord Vishnu. Conventionally a solo dance performed by female artists, it emotes a play through dancing and singing where the song is customarily in Manipravala which is a mix of Sanskrit and Malayalam language and the recitation may be either performed by the dancer herself or by a vocalist with the music style being Carnatic.Mohiniattam evolved from the state of Kerala which also has an association with the old tradition of Lasya style of dancing. The temple sculptures of the state are the earliest manifestations of Mohiniattam or other dance forms similar to it. Mohiniattam poses are also palpable from the various feminine sculptures that adorn the 11th century Vishnu temple at Trikodithanam, and the Kidangur Subramanya temple. The Lasya theme was incorporated by Malayalam bards and playwrights, a fact evident from the text-based records starting from the 12th century. The 16th century book titled ‘Vyavaharamala’ written by scholar, poet, author and astrologer Mazhamangalam Narayanan Namboodiri is the first known book that mentions the term Mohiniyattam in connection with a payment due to a Mohiniyattam dancer. While discussing about various performing art forms of Kerala, renowned poet Kunchan Nambiar in his 17th century book ‘Gosha Yatra’ mentioned about Mohiniyattam. By that time this dance form had emerged as one of the classical art forms of the state. The 18th century Sanskrit treatise ‘Balarama Bharatam’ on natyam written by the king of Travancore Karthika Thirunal Bala Rama Varma (considered to be a significant second.",
        desc:"  Lord Vishnu once came to the aid of the Gods by assuming the form of the beautiful enchantress Mohini to seduce their arch nemesis, the Asuras (demons). "
    },
    {
        id:4,
        name:"padayani",
        images:"padayani.jpg",
        desc2:"Padayani is a ritual art form performed at Bhadrakali temples located on the banks of river Pampa. According to mythology, this ritualistic dance commemorates the dance performed by Lord Shiva and the other Gods to appease Goddess Durga, whose anger could not be quenched even after annihilating the demon, Darika.  Popular places where Padayani is performed are Kadammanitta, Kottangal, Othara, Kunnanthaanam and many other temples in south Kerala.  Though traditionally, it lasted for nearly two weeks, now-a days, it is held for durations that are as short as a single day. Kolam thullal is the major portion of Padayani performance.  Kolam is a masque made by drawing images on the leaves of the arecanut palm. Wearing this Kolam, padayani dancer performs the ritual dance in devotion. These Kolam are representations of spiritual forces or divine characters, and are depicted with terrifying and spectacular face masks and head gear, painted in vivid colours like deep red and black, using natural powders. They include the Ganapathi Kolam, the Yakshi Kolam, the Pakshi Kolam, the Maadan Kolam, the Kaalan Kolam, the Maruthaa Kolam, the Pishachu Kolam, the Bhairavi Kolam, the Gandharvan Kolam and the Mukilan Kolam. Padayani is essentially a communal activity where villagers are actively involved in collecting arecanut palms and participate in the making kolam.",
        desc:" Padayani is a ritual art form performed at Bhadrakali temples located on the banks of river Pampa.  "
    },
    {
    id:5,
        name:"nangiyarkoothu",
        images:"nangi.jpg",
        desc2:"Koothu is a socio-religious art performed in the Koothambalam or the Koothuthara of temples, either independently or as part of Kutiyattam. It is a solo narrative performance interspersed with mime and comic interludes. The Chakkiar does the role of 'Vidushaka'or the wise jester. Through his inimitable narration of stories from the epics (The Ramayana and The Mahabharatha), the Chakkiar satirises the manners and customs of the time. No one is above the butt of his ridicule. His wit ranges from innocent mockery to veiled innuendoes, barbed pun and pungent invectives. Koothu is intermittently accompanied by the percussion instrument Mizhavu. The Nangyar Koothu is a variation of the Koothu performed by the Nangiars or the female members of the Chakkiar community. This is a solo dance drama mainly centred on the legends of Sree Krishna. Verses are sung and interpreted through mime and dance. The mudras, though the same as in Kootiyattam, are even more elaborate. The art form is still performed in temples like Vadakkumnathan temple at Thrissur, Sri Krishna temple at Ambalappuzha, Koodal Manikyam temple at Irinjalakkuda and Kumaranalloor temple at Kottayam.",
        desc:" Nangyarkoothu, a classical art form of Kerala, is a popular temple art form of Kerala."
},
{
    id:6,
        name:"kalaripayattu",
        images:"kalaripayattu.jpg",
        desc2:"Kalaripayattu, also spelled as Kalarippayattu is an ancient martial art indigenous to Kerala, a small state in the southern tip of India, but is known and practised throughout the globe today.  The exact time of its origin however cannot be fixed with any sense of certainty. Some argue that in its crudest form, Kalaripayattu was a means by which the earliest inhabitants of this wooded and mountainous terrain hunted wild animals before it was refined into a systematic mode of combat that was effective enough to overpower enemies and defend themselves.Myth-lovers like to believe that Kalaripayattu has a hoary past, having been introduced by Lord Parasurama, the sixth incarnation of Lord Vishnu, after he reclaimed the land of Kerala from the Arabian Sea. While historians reject such claims, there is no consensus among them either, with their pegging the time of its birth anywhere between 200 BCE and 600 CE, and its cresting popularity between the 14th and 16th centuries. But what has never varied, amidst all these claims and counter-claims, is the awe with which chroniclers and poets of different periods recorded the complexity of the techniques, the liquid beauty of the moves, and the enviable elasticity of the practitioners of Kalaripayattu.",
        desc:"Kalaripayattu is the martial art form of Kerala. Kalaripayattu’s influence can be seen in most of the art forms of Kerala"
},
{
    id:7,
        name:"bharathanattiyam",
        images:"bh.jpg",
        desc2:"Bharatanatyam is a dance of Tamil Nadu in southern India. It traces its origins back to the Natyashastra, an ancient treatise on theatre written by the mythic priest Bharata. Originally a temple dance for women, bharatanatyam often is used to express Hindu religious stories and devotions. It was not commonly seen on the public stage until the 20th century. The dance movements are characterized by bent legs, while feet keep rhythm. Hands may be used in a series of mudras, or symbolic hand gestures, to tell a story.",
        desc:"Bharatanatyam is a dance of Tamil Nadu in southern India."
},
{
    id:8,
        name:"chakkyarkoothu",
        images:"ch.jpg",
        desc2:"Koothu is an art form in which the stories of Hindu mythology and epics are orally rendered primarily with the support of acting and hand gestures. In the olden days, it was confined to temple premises.  Only the members of the Chakyar community performed this art form and hence the name Chakyar Koothu. This was performed in temple theatres called Koothambalam. In Chakyar Koothu the entire story is presented by a single performer. The costumes are that of a court jester. Facial make-up is done with rice powder, turmeric powder and black powder. He wears an ornament in one ear and a betel leaf in the other. An accompanying artist plays the percussion instrument Mizhavu in the background.The highlights of Chakyar Koothu, is satire, social criticism, humor and related stories or episodes presented during the performance.  In the olden days of royalty, the Chakyar had the right to criticise even the King and his acts while performing.  The practice was that the audience should listen to the Chakyar and accept his criticisms.  Any opposition to comments made by the Chakyar while performing would have led to an end in the performance of the art form in that premises for ever.",
       desc:"Koothu is an art form in which the stories of Hindu mythology and epics are orally rendered primarily with the support of acting and hand gestures. In the olden days, it was confined to temple premises.  Only the members of the Chakyar community performed this art form and hence the name Chakyar Koothu."
},
{
    id:9,
        name:"kudiyattam",
        images:"ku.jpg",
       desc2:"The ancient Sanskrit theatrical art form of the state, Kutiyattam is Kerala’s distinctive stage interpretation of the very early Sanskrit drama as dance drama. Kutiyattam (Koodiyattam), which is around 2000 years old, has been accepted as one of the 'Masterpieces of Oral and Intangible Heritage of Humanity' by the UNESCO. It is usually performed only in temple theatres known as Koothambalam by members of the Chakyar and Nambyar castes till the first half of the 20th century. Only through rigorous training lasting many years one can aspire to master the craft of Kutiyattam.The word Kutiyattam literally means . There are four methods or types of acting has been mentioned in Sage Bharata’s Natya Shastra – aangikam (expression using different parts of the body), vaachikam (expression through speech), sathvikam (expression of physical reactions to emotions) and aahaaryam (expression through costume, ornaments and props) are all woven into Koodiyattam performances. A typical Koodiyattam performance involves elaborate and lengthy acting sequences using hand gestures and distinctive modes of acting like Ilakiyaattom, Pakarnnaatttom and Irunnaattom.",
        desc:"The ancient Sanskrit theatrical art form of the state, Kutiyattam is Kerala’s distinctive stage interpretation of the very early Sanskrit drama as dance drama. Kutiyattam (Koodiyattam), which is around 2000 years old, has been accepted as one of the 'Masterpieces of Oral and Intangible Heritage of Humanity' by the UNESCO."
}

]